name: "CICD Actions"
author: "Alan Graham"
branding:
  icon: 'anchor'
  color: 'blue'
description: "Build, test, and push repository"
inputs:
  tasks:
    description: "Comma separated list of tasks to run"
    required: true
  image_name:
    description: "The name of the image you would like to push"
    required: false
  image_tar:
    description: "The path to the tar of the built image"
    required: false
  registry:
    description: "The registry URL"
    required: false
  registry_username:
    description: "The login username for the registry"
    required: false
  registry_password:
    description: "The login password for the registry"
    required: false
  tests:
    description: "Tests that the image should run before pushing, comma separated"
    required: false
  build_artifact:
    description: "Only build the image and store as an artifact"
    required: false
  test_env_file:
    description: "Environment file for running tests"
    required: false
  cypress_record_key:
    description: "Record key for cypress"
    required: false
  cypress_record_enabled:
    description: "Enable cypress recording"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
