name: "CICD Actions"
author: "Alan Graham"
branding:
  icon: 'anchor'
  color: 'blue'
description: "Build, test, and push repository"
inputs:
  tasks:
    description: "Comma separated list of tasks to run"
    required: true
  image_name:
    description: "The name of the image you would like to push"
    required: false
  image_namespace:
    description: "The namespace of the image you would like to push"
    required: false
  image_tag:
    description: "The image tag to use (defaults to branch)"
    required: false
  image_tag_style:
    description: "The style of the image tag [branch | sha]"
    required: false
  image_tar:
    description: "The path to the tar of the built image"
    required: false
  use_temporary_remote_image:
    description: "Use temporary remote image when pushing or pulling"
    required: false
  registry_url:
    description: "The registry URL"
    required: false
  registry_username:
    description: "The login username for the registry"
    required: false
  registry_password:
    description: "The login password for the registry"
    required: false
  aws_region:
    description: "AWS Region"
    required: false
  aws_access_key:
    description: "AWS Access Key"
    required: false
  aws_secret_access_key:
    description: "AWS Secret Access Key"
    required: false
  tests:
    description: "Tests that the image should run before pushing, comma separated"
    required: false
  build_artifact:
    description: "Only build the image and store as an artifact"
    required: false
  build_from_cache:
    description: "Attempt to pull image to use as cache"
    required: false
  image_env_file:
    description: "Environment file for running image"
    required: false
  cypress_record_key:
    description: "Record key for cypress"
    required: false
  cypress_record_enabled:
    description: "Enable cypress recording"
    required: false
  cypress_use_deploy_url:
    description: "Determine deploy URL based on branch for Cypress"
    required: false
  cypress_base_url:
    description: "Use base URL for Cypress"
    required: false
  cypress_parallel_count:
    description: "Number of instances to run in parallel for Cypress"
    required: false
  kube_cluster_name:
    description: "Kube cluster name"
    required: false
  copy_paths:
    description: "Paths to copy"
    required: false
  lambda_function_name:
    description: "Lambda function name"
    required: false
  aptible_environment:
    description: "Aptible environment name"
    required: false
  aptible_app:
    description: "Aptible app name"
    required: false
  aptible_email:
    description: "Aptible account email"
    required: false
  aptible_password:
    description: "Aptible account password"
    required: false
  deploy_url_env_var:
    description: "Deploy url environment variable"
    required: false
  git_tags:
    description: "Git tags to reference"
    required: false
outputs:
  deploy_url:
    description: "Deploy URL for this branch"
  skip:
    description: "Indicates should skip next step"
runs:
  using: 'docker'
  image: 'Dockerfile'
