name: "CICD Actions"
author: "Alan Graham"
branding:
  icon: 'anchor'
  color: 'blue'
description: "Build, test, and push repository"
inputs:
  tasks:
    description: "Comma separated list of tasks to run"
    required: true
  image_name:
    description: "The name of the image you would like to push"
    required: false
  image_namespace:
    description: "The namespace of the image you would like to push"
    required: false
  image_tar:
    description: "The path to the tar of the built image"
    required: false
  registry_url:
    description: "The registry URL"
    required: false
  registry_username:
    description: "The login username for the registry"
    required: false
  registry_password:
    description: "The login password for the registry"
    required: false
  aws_region:
    description: "AWS Region"
    required: false
  aws_access_key:
    description: "AWS Access Key"
    required: false
  aws_secret_access_key:
    description: "AWS Secret Access Key"
    required: false
  tests:
    description: "Tests that the image should run before pushing, comma separated"
    required: false
  build_artifact:
    description: "Only build the image and store as an artifact"
    required: false
  image_env_file:
    description: "Environment file for running image"
    required: false
  cypress_record_key:
    description: "Record key for cypress"
    required: false
  cypress_record_enabled:
    description: "Enable cypress recording"
    required: false
  kube_cluster_name:
    description: "Kube cluster name"
    required: false
  copy_paths:
    description: "Paths to copy"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
