FROM cypress/browsers:chrome69

RUN apt-get update
RUN apt-get install -qy libgbm-dev
RUN npm install --save-dev cypress@5.0.0

ADD ./cypress cypress
ADD .git .git
ADD .github/cypress.env.json cypress.env.json
ADD .github/cypress.json cypress.json

ENTRYPOINT ["/node_modules/.bin/cypress"]


