name: "CICD Actions - Build, Test, Push"
author: "Alan Graham"
branding:
  icon: 'anchor'
  color: 'blue'
description: "Build, test, and push repository"
inputs:
  tasks:
    description: "Comma separated list of tasks to run"
    required: true
  name:
    description: "The name of the image you would like to push"
    required: true
  username:
    description: "The login username for the registry"
    required: true
  password:
    description: "The login password for the registry"
    required: true
  registry:
    description: "The registry URL"
    required: true
  tests:
    description: "Tests that the image should run before pushing, comma separated"
    required: false
  build_artifact:
    description: "Only build the image and store as an artifact"
    required: false
  test_env_file:
    description: "Environment file for running tests"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
